services:
  api:
    build: .
    container_name: sarbam_backend
    ports:
      - "8000:80"
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    command: gunicorn sarbam_mail.wsgi:application --bind 0.0.0.0:8000

  postgres:
    image: postgres:17
    container_name: postgres_container
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:6
    container_name: redis_server

  celery:
    build: .
    container_name: celery_worker
    command: celery -A sarbam_mail.celery worker --loglevel=info
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data: